apiVersion: webapp.my.domain/v1
kind: Guestbook
metadata:
  name: guestbook-sample
spec:
  foo: bar
  size: 2
  configMapName: "config"
  StatefulSet:
    spec:
      selector:
        matchLabels:
          app: guestBook
      template:
        spec:
          containers:
            - name: memcached
              image: memcached:1.4.36-alpine
          ports:
            - containerPort: 11211
              name: memcached
          command:
          - /bin/sh
            - "-c"
            - |
            set -x
            memcached -m=64 -o modern -v