apiVersion: webapp.my.domain/v1
kind: Guestbook
metadata:
  name: guestbook-sample
spec:
  # Add fields here
  foo: bar
  size: 2
  configMapName: "aa"
  StatefulSet:
    template:
      spec:
        containers:
          - name: memcached
            image: memcached:1.4.36-alpine